title: AquiGorka
email: gorka@aquigorka.com
description: Sigue aprendiendo
twitter_username: AquiGorka
github_username: AquiGorka

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
