# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-paginate

# Permalinks
permalink: pretty

# Setup
url: https://aquigorka.github.io

# Set to '' in case of hosting on GitHub pages,
# i.e. `http://<username>.github.io`
baseurl: '' 

title: AquiGorka

# Pagination
paginate: 7
paginate_path: '/page-:num/'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         >
  Sigue aprendiendo

# The tags listed as entries in the sidebar
#sidebar_tags: [ideas]

# Fallback image and color if not overwritten for tag or post
image: /public/img/night-dark-blur-blurred.jpg
color: '#1A6158'

# Fonts
font:                '"PT Serif", Georgia, serif'
font_accent:         '"Roboto Slab", "PT Serif", Georgia, serif'
load_google_fonts:   'Roboto+Slab:700|PT+Serif:400,400italic,700,700italic'

# About yourself
author:
  name: 'Gorka Ludlow'

  # This photo will be used in the about section
  photo: https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAiYAAAAJDU5OTcyODQ5LTA0YmMtNDM1ZS05MzU5LTc4NTc4YmFjNDdiNQ.jpg
  photo2x: https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAiYAAAAJDU5OTcyODQ5LTA0YmMtNDM1ZS05MzU5LTc4NTc4YmFjNDdiNQ.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:             |
  Mi nombre es Gorka. Hoy en día me llama mucho la atención todo lo que tenga que ver con realidad virtual, realidad aumentada, videojuegos e interfaces de control humano-software.
  |
  https://github.com/AquiGorka
  |
  http://AquiGorka.net

  # Social media icons in sidebar
  # Comment/uncommet to show/hide
  # Icons appear in order, can be rearranged:
  social:
    twitter: AquiGorka
    github: AquiGorka
    linkedin: gorka-ludlow

# Remove to disable Google Anaylics
google_analytics_id: 'UA-84025722-2'

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: true

compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all
  ignore:
    envs: [local]

sass:
  style: compressed

